# Study01 : NUMPY

행렬을 지원하는 라이브러리로, 데이터에 대해 많이 사용된다. 여러 피처를 사용하기에 필수적으로 사용된다.

아래는 셀의 마지막 표현식을 출력해주는 함수이다.

In [2]:
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"


a = 3
a

3

행렬 만들기

<hr>

[[element1], [element2]] 이렇게 생성하는것과 기본적으론 차이가 없지만, np를 사용해 만들었을 경우 numpy가 지원하는 함수를 사용할 수 있게 된다.

In [7]:
import numpy as np

a = np.array([[0,1,2], [3,4,5]])
b = [[0,1,2], [3,4,5]]

a == b

array([[ True,  True,  True],
       [ True,  True,  True]])

In [14]:
"배열의 차원"
a.ndim

"배열의 크기"
a.shape

"1행 1열 원소"
a[0][0]

'배열의 차원'

2

'배열의 크기'

(2, 3)

'1행 1열 원소'

0

In [20]:
"range : i < num 까지의 numpy배열 생성"
a = np.arange(10) 
a

'range : i < num 까지의 numpy배열 생성'

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
"reshape : 1차원 배열이었던 a를 다차원 배열, 행렬로 변경"
b = a.reshape(2,5)
b

'reshape : 1차원 배열이었던 a를 다차원 배열, 행렬로 변경'

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [26]:
"0 행렬 만들기"
x = np.zeros((3,4))
x

"모든 원소가 1인 행렬 만들기"
y = np.ones((3,4))
y

'0 행렬 만들기'

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

'단위 행렬 만들기'

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [27]:
"단위 행렬 만들기"
i = np.identity(3)
i


'단위 행렬 만들기'

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [32]:
"무작위 행렬 만들기 - 균등분포를 따름, [0,1) 범위에서 무작위로 선택됨."
r = np.random.rand(3,3)
r

"무작위 행렬 만들기 - 정규분포를 따름, 평균 0 표준편차 1에서 무작위 선택"

k = np.random.randn(3,3)
k

'무작위 행렬 만들기 - 균등분포를 따름, [0,1) 범위에서 무작위로 선택됨.'

array([[0.51015327, 0.79487638, 0.11562888],
       [0.13898352, 0.8580252 , 0.7335103 ],
       [0.39646639, 0.83821128, 0.21985937]])

'무작위 행렬 만들기 - 정규분포를 따름, 평균 0 표준편차 1에서 무작위 선택'

array([[ 1.10391783,  1.16505027,  0.27393011],
       [-0.40660679, -0.2788828 , -0.66057214],
       [-2.01724452,  0.63354288, -0.61188475]])

# Numpy가 제공하는 operations

In [45]:
a = np.array([[0,1], [2,3]])
b = np.array([[4,5], [6,7]])

"Scalar 배"
a * 10 

"행렬 합"
a+b

"같은 인덱스 값끼리 곱하기 (행렬곱 아님!!)"
a*b

'Scalar 배'

array([[ 0, 10],
       [20, 30]])

'행렬 합'

array([[ 4,  6],
       [ 8, 10]])

'같은 인덱스 값끼리 곱하기 (행렬곱 아님!!)'

array([[ 0,  5],
       [12, 21]])

In [48]:
"행렬 곱 : dot 사용"
a.dot(b)

"행렬 곱 : @ 사용"
a @ b

"전치"
a.T

'행렬 곱 : dot 사용'

array([[ 6,  7],
       [26, 31]])

'행렬 곱 : @ 사용'

array([[ 6,  7],
       [26, 31]])

'전치'

array([[0, 2],
       [1, 3]])

# Indexing, Slicing

In [49]:
a = np.arange(20).reshape(4,5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [50]:
"3행 3열 원소 접근하기"
a[2,2]

": 슬라이싱 사용하기"
a[0:2, 0:2]

a[0:2, :]

'3행 3열 원소 접근하기'

12

': 슬라이싱 사용하기'

array([[0, 1],
       [5, 6]])

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

# Stacking

In [51]:
a = np.array([[1, 1],[0, 1]])

b = np.array(np.random.rand(2, 2))

a
b

array([[1, 1],
       [0, 1]])

array([[0.99670526, 0.75656941],
       [0.47967811, 0.48020169]])

In [52]:
"행렬 두개 붙이기"
"새로운 행으로 붙이기 (세로)"
np.vstack((a,b))

"새로운 열로 붙이기 (가로)"
np.hstack((a,b))

'행렬 두개 붙이기'

'새로운 행으로 붙이기 (세로)'

array([[1.        , 1.        ],
       [0.        , 1.        ],
       [0.99670526, 0.75656941],
       [0.47967811, 0.48020169]])

'새로운 열로 붙이기 (가로)'

array([[1.        , 1.        , 0.99670526, 0.75656941],
       [0.        , 1.        , 0.47967811, 0.48020169]])

# Axis (기준 정하기)

axis = 0 : 행방향으로 연산 할거야

aixs = 1 : 열방향으로 연산 할거야

이건 좀 쉽게 생각하려고 이러는거고 아래는 어떻게 생각해야할지이다.

[[1,2,3], [4,5,6]] 이라는 array가 있다고 생각해보자. 

axis = 0 이면 [1,2,3] -> [4,5,6] 두개에 대한 연산을 진행하는것이다.

axis = 1 이면 1,2,3     4,5,6 별개로 원소들끼리 연산

즉 1이 커질때마다 []를 하나 벗는다고 생각하면 될 것이다.

In [54]:
a = np.arange(6).reshape(2,3)
a

"행으로 더하기"
a.sum(axis = 0)

"열으로 더하기"
a.sum(axis = 1)

array([[0, 1, 2],
       [3, 4, 5]])

'행으로 더하기'

array([3, 5, 7])

'열으로 더하기'

array([ 3, 12])

In [56]:
a = np.array([[20,10], [2,1]])
a

np.sort(a, axis = 0)

np.sort(a, axis = 1)

array([[20, 10],
       [ 2,  1]])

array([[ 2,  1],
       [20, 10]])

array([[10, 20],
       [ 1,  2]])

In [58]:
a = np.arange(10).reshape(5,2)
a

"max"
np.max(a)
"min"
np.min(a)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

'max'

9

'min'

0

In [59]:
a = np.array([[1, 2], [3, 4]])
a 

"평균 구하기"
np.mean(a)
np.mean(a, axis = 0)
np.mean(a, axis = 1)

"표준편차 구하기"
np.std(a)
np.std(a, axis = 0)
np.std(a, axis = 1)

"분산 구하기"
np.var(a)

array([[1, 2],
       [3, 4]])

'평균 구하기'

2.5

array([2., 3.])

array([1.5, 3.5])

'표준편차 구하기'

1.118033988749895

array([1., 1.])

array([0.5, 0.5])

'분산 구하기'

1.25