# Chapter 8 : Attention

In [2]:
import numpy as np 

T, H = 5, 4
hs = np.random.randn(T, H)
a = np.array([0.8, 0.1, 0.03, 0.05, 0.02])

ar = a.reshape(5, 1).repeat(4, axis=1)
print('=' * 20)
print(ar.shape)
print(ar)

t = hs * ar
print('=' * 20)
print(t.shape)
print(t)

c = np.sum(t, axis=0)
print('=' * 20)
print(c.shape)
print(c)

(5, 4)
[[0.8  0.8  0.8  0.8 ]
 [0.1  0.1  0.1  0.1 ]
 [0.03 0.03 0.03 0.03]
 [0.05 0.05 0.05 0.05]
 [0.02 0.02 0.02 0.02]]
(5, 4)
[[-0.54254811 -0.20333065  1.30408333 -0.09887616]
 [-0.00294172  0.04743715 -0.11080295 -0.16911239]
 [-0.04375525  0.04301256  0.0074144  -0.02725987]
 [ 0.00325344 -0.00586551 -0.00629445  0.00202656]
 [-0.01432782  0.00278698 -0.00566155 -0.00885147]]
(4,)
[-0.60031946 -0.11595948  1.18873879 -0.30207333]
